-- ==================== SEED DATA ====================

-- Roles
INSERT [dbo].[Roles] ([ID], [Title]) VALUES (1, N'Administrator')
INSERT [dbo].[Roles] ([ID], [Title]) VALUES (2, N'Điều hành viên')
INSERT [dbo].[Roles] ([ID], [Title]) VALUES (3, N'Nhân viên bán vé')
GO

-- Countries
SET IDENTITY_INSERT [dbo].[Countries] ON
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (1, N'Afghanistan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (2, N'Albania')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (3, N'Algeria')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (4, N'Andorra')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (5, N'Angola')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (6, N'Antigua & Deps')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (7, N'Argentina')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (8, N'Armenia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (9, N'Australia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (10, N'Austria')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (11, N'Azerbaijan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (12, N'Bahamas')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (13, N'Bahrain')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (14, N'Bangladesh')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (15, N'Barbados')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (16, N'Belarus')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (17, N'Belgium')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (18, N'Belize')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (19, N'Benin')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (20, N'Bhutan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (21, N'Bolivia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (22, N'Bosnia Herzegovina')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (23, N'Botswana')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (24, N'Brazil')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (25, N'Brunei')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (26, N'Bulgaria')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (27, N'Burkina')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (28, N'Burundi')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (29, N'Cambodia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (30, N'Cameroon')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (31, N'Canada')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (32, N'Cape Verde')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (33, N'Central African Rep')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (34, N'Chad')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (35, N'Chile')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (36, N'China')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (37, N'Colombia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (38, N'Comoros')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (39, N'Congo')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (40, N'Congo {Democratic Rep}')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (41, N'Costa Rica')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (42, N'Croatia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (43, N'Cuba')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (44, N'Cyprus')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (45, N'Czech Republic')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (46, N'Denmark')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (47, N'Djibouti')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (48, N'Dominica')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (49, N'Dominican Republic')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (50, N'East Timor')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (51, N'Ecuador')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (52, N'Egypt')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (53, N'El Salvador')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (54, N'Equatorial Guinea')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (55, N'Eritrea')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (56, N'Estonia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (57, N'Ethiopia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (58, N'Fiji')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (59, N'Finland')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (60, N'France')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (61, N'Gabon')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (62, N'Gambia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (63, N'Georgia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (64, N'Germany')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (65, N'Ghana')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (66, N'Greece')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (67, N'Grenada')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (68, N'Guatemala')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (69, N'Guinea')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (70, N'Guinea-Bissau')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (71, N'Guyana')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (72, N'Haiti')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (73, N'Honduras')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (74, N'Hungary')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (75, N'Iceland')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (76, N'India')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (77, N'Indonesia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (78, N'Iran')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (79, N'Iraq')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (80, N'Ireland {Republic}')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (81, N'Israel')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (82, N'Italy')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (83, N'Ivory Coast')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (84, N'Jamaica')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (85, N'Japan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (86, N'Jordan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (87, N'Kazakhstan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (88, N'Kenya')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (89, N'Kiribati')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (90, N'Korea North')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (91, N'Korea South')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (92, N'Kosovo')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (93, N'Kuwait')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (94, N'Kyrgyzstan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (95, N'Laos')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (96, N'Latvia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (97, N'Lebanon')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (98, N'Lesotho')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (99, N'Liberia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (100, N'Libya')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (101, N'Liechtenstein')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (102, N'Lithuania')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (103, N'Luxembourg')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (104, N'Macedonia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (105, N'Madagascar')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (106, N'Malawi')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (107, N'Malaysia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (108, N'Maldives')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (109, N'Mali')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (110, N'Malta')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (111, N'Marshall Islands')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (112, N'Mauritania')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (113, N'Mauritius')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (114, N'Mexico')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (115, N'Micronesia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (116, N'Moldova')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (117, N'Monaco')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (118, N'Mongolia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (119, N'Montenegro')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (120, N'Morocco')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (121, N'Mozambique')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (122, N'Myanmar, {Burma}')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (123, N'Namibia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (124, N'Nauru')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (125, N'Nepal')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (126, N'Netherlands')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (127, N'New Zealand')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (128, N'Nicaragua')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (129, N'Niger')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (130, N'Nigeria')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (131, N'Norway')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (132, N'Oman')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (133, N'Pakistan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (134, N'Palau')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (135, N'Panama')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (136, N'Papua New Guinea')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (137, N'Paraguay')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (138, N'Peru')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (139, N'Philippines')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (140, N'Poland')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (141, N'Portugal')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (142, N'Qatar')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (143, N'Romania')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (144, N'Russian Federation')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (145, N'Rwanda')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (146, N'St Kitts & Nevis')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (147, N'St Lucia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (148, N'Saint Vincent & the Grenadines')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (149, N'Samoa')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (150, N'San Marino')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (151, N'Sao Tome & Principe')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (152, N'Saudi Arabia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (153, N'Senegal')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (154, N'Serbia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (155, N'Seychelles')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (156, N'Sierra Leone')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (157, N'Singapore')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (158, N'Slovakia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (159, N'Slovenia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (160, N'Solomon Islands')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (161, N'Somalia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (162, N'South Africa')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (163, N'South Sudan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (164, N'Spain')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (165, N'Sri Lanka')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (166, N'Sudan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (167, N'Suriname')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (168, N'Swaziland')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (169, N'Sweden')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (170, N'Switzerland')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (171, N'Syria')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (172, N'Taiwan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (173, N'Tajikistan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (174, N'Tanzania')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (175, N'Thailand')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (176, N'Togo')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (177, N'Tonga')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (178, N'Trinidad & Tobago')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (179, N'Tunisia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (180, N'Turkey')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (181, N'Turkmenistan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (182, N'Tuvalu')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (183, N'Uganda')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (184, N'Ukraine')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (185, N'United Arab Emirates')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (186, N'United Kingdom')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (187, N'United States')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (188, N'Uruguay')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (189, N'Uzbekistan')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (190, N'Vanuatu')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (191, N'Vatican City')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (192, N'Venezuela')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (193, N'Việt Nam')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (194, N'Yemen')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (195, N'Zambia')
INSERT [dbo].[Countries] ([ID], [Name]) VALUES (196, N'Zimbabwe')
SET IDENTITY_INSERT [dbo].[Countries] OFF
GO

-- Offices
SET IDENTITY_INSERT [dbo].[Offices] ON
INSERT [dbo].[Offices] ([ID],[CountryID],[Title],[Phone],[Contact]) VALUES (1,1,N'Văn phòng Hà Nội',N'024-1234-5678',N'hanoi@skyblue.vn')
INSERT [dbo].[Offices] ([ID],[CountryID],[Title],[Phone],[Contact]) VALUES (2,1,N'Văn phòng TP.HCM',N'028-8765-4321',N'hcm@skyblue.vn')
INSERT [dbo].[Offices] ([ID],[CountryID],[Title],[Phone],[Contact]) VALUES (3,1,N'Văn phòng Đà Nẵng',N'0236-123-4567',N'danang@skyblue.vn')
SET IDENTITY_INSERT [dbo].[Offices] OFF
GO

-- Users
SET IDENTITY_INSERT [dbo].[Users] ON
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (1, 1, N'admin1', N'123456', N'Quản Trị 1', N'Nguyễn', 1, '1985-05-15', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (2, 2, N'operator1', N'123456', N'Điều Hành 1', N'Nguyễn', 1, '1990-08-20', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (3, 3, N'agent1', N'123456', N'Bán Vé 1', N'Nguyễn', 1, '1995-03-10', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (4, 1, N'admin2', N'123456', N'Quản Trị 2', N'Trần', 2, '1988-06-25', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (5, 2, N'operator2', N'123456', N'Điều Hành 2', N'Trần', 2, '1992-11-12', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (6, 3, N'agent2', N'123456', N'Bán Vé 2', N'Trần', 2, '1997-04-18', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (7, 1, N'admin3', N'123456', N'Quản Trị 3', N'Lê', 3, '1987-01-15', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (8, 2, N'operator3', N'123456', N'Điều Hành 3', N'Lê', 3, '1991-09-22', 1)
INSERT [dbo].[Users] ([ID],[RoleID],[Email],[Password],[FirstName],[LastName],[OfficeID],[Birthdate],[Active])
VALUES (9, 3, N'agent3', N'123456', N'Bán Vé 3', N'Lê', 3, '1996-07-30', 1)
SET IDENTITY_INSERT [dbo].[Users] OFF
GO

-- Airports
SET IDENTITY_INSERT [dbo].[Airports] ON
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (1,193,'HAN',N'Sân bay Nội Bài')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (2,193,'SGN',N'Sân bay Tân Sơn Nhất')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (3,193,'DAD',N'Sân bay Đà Nẵng')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (4,2,'BKK',N'Suvarnabhumi Airport')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (5,3,'SIN',N'Singapore Changi Airport')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (6,4,'KUL',N'Kuala Lumpur International Airport')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (7,5,'NRT',N'Narita International Airport')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (8,6,'ICN',N'Incheon International Airport')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (9,193,'CXR',N'Sân bay Cam Ranh')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (10,193,'PQC',N'Sân bay Phú Quốc')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (11,193,'HPH',N'Sân bay Cát Bi')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (12,193,'HUI',N'Sân bay Phú Bài')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (13,193,'VII',N'Sân bay Vinh')
INSERT [dbo].[Airports] ([ID],[CountryID],[IATACode],[Name]) VALUES (14,193,'VCA',N'Sân bay Cần Thơ')
SET IDENTITY_INSERT [dbo].[Airports] OFF
GO

-- Routes
SET IDENTITY_INSERT [dbo].[Routes] ON
INSERT [dbo].[Routes] ([ID],[DepartureAirportID],[ArrivalAirportID],[Distance],[FlightTime]) VALUES (1,1,2,1166,130)
INSERT [dbo].[Routes] ([ID],[DepartureAirportID],[ArrivalAirportID],[Distance],[FlightTime]) VALUES (2,1,3,612,75)
INSERT [dbo].[Routes] ([ID],[DepartureAirportID],[ArrivalAirportID],[Distance],[FlightTime]) VALUES (3,2,3,608,70)
INSERT [dbo].[Routes] ([ID],[DepartureAirportID],[ArrivalAirportID],[Distance],[FlightTime]) VALUES (4,1,4,1420,140)
INSERT [dbo].[Routes] ([ID],[DepartureAirportID],[ArrivalAirportID],[Distance],[FlightTime]) VALUES (5,2,5,1153,125)
INSERT [dbo].[Routes] ([ID],[DepartureAirportID],[ArrivalAirportID],[Distance],[FlightTime]) VALUES (6,1,7,3670,320)
SET IDENTITY_INSERT [dbo].[Routes] OFF
GO

-- Aircrafts
SET IDENTITY_INSERT [dbo].[Aircrafts] ON
INSERT [dbo].[Aircrafts] ([ID],[Name],[MakeModel],[TotalSeats],[FirstClassSeats],[EconomySeats],[BusinessSeats]) VALUES (1,N'VN-A001',N'Boeing 787-9',296,8,248,40)
INSERT [dbo].[Aircrafts] ([ID],[Name],[MakeModel],[TotalSeats],[FirstClassSeats],[EconomySeats],[BusinessSeats]) VALUES (2,N'VN-A002',N'Airbus A350-900',305,4,261,40)
INSERT [dbo].[Aircrafts] ([ID],[Name],[MakeModel],[TotalSeats],[FirstClassSeats],[EconomySeats],[BusinessSeats]) VALUES (3,N'VN-A003',N'Boeing 737-800',189,0,177,12)
INSERT [dbo].[Aircrafts] ([ID],[Name],[MakeModel],[TotalSeats],[FirstClassSeats],[EconomySeats],[BusinessSeats]) VALUES (4,N'VN-A004',N'Boeing 777-300ER',368,4,324,40)
INSERT [dbo].[Aircrafts] ([ID],[Name],[MakeModel],[TotalSeats],[FirstClassSeats],[EconomySeats],[BusinessSeats]) VALUES (5,N'VN-A005',N'Airbus A321neo',203,0,195,8)
INSERT [dbo].[Aircrafts] ([ID],[Name],[MakeModel],[TotalSeats],[FirstClassSeats],[EconomySeats],[BusinessSeats]) VALUES (6,N'VN-A006',N'Airbus A330-900',300,0,264,36)
INSERT [dbo].[Aircrafts] ([ID],[Name],[MakeModel],[TotalSeats],[FirstClassSeats],[EconomySeats],[BusinessSeats]) VALUES (7,N'VN-A007',N'Boeing 787-10',367,4,339,24)
SET IDENTITY_INSERT [dbo].[Aircrafts] OFF
GO

-- CabinTypes
SET IDENTITY_INSERT [dbo].[CabinTypes] ON
INSERT [dbo].[CabinTypes] ([ID],[Name],[PriceMultiplier]) VALUES (1,N'Hạng Phổ Thông',1)
INSERT [dbo].[CabinTypes] ([ID],[Name],[PriceMultiplier]) VALUES (2,N'Hạng Thương Gia',2.5)
INSERT [dbo].[CabinTypes] ([ID],[Name],[PriceMultiplier]) VALUES (3,N'Hạng Nhất',4)
SET IDENTITY_INSERT [dbo].[CabinTypes] OFF
GO

-- Amenities
SET IDENTITY_INSERT [dbo].[Amenities] ON
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (1,N'Hành lý 20kg',200000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (2,N'Hành lý 30kg',350000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (3,N'Suất ăn nóng',150000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (4,N'Wi-Fi',100000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (5,N'Chỗ ngồi ưu tiên',250000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (6,N'Phòng chờ Thương gia',450000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (7,N'Lối đi ưu tiên (Fast Track)',180000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (8,N'Hành lý ký gửi 40kg',500000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (9,N'Suất ăn nóng cao cấp',250000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (10,N'Đưa đón sân bay xe sang',600000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (11,N'Bảo hiểm du lịch cao cấp',120000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (12,N'Chăm sóc em bé đi kèm',150000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (13,N'Vận chuyển thú cưng',800000)
INSERT [dbo].[Amenities] ([ID],[Service],[Price]) VALUES (14,N'Bộ kit ngủ cao cấp',90000)
SET IDENTITY_INSERT [dbo].[Amenities] OFF
GO

-- AmenitiesCabinType (default amenities per cabin)
-- Economy (1)
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (1,1) -- Hành lý 20kg
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (1,14) -- Bộ kit ngủ cao cấp

-- Business (2)
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (2,2) -- Hành lý 30kg
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (2,9) -- Suất ăn nóng cao cấp
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (2,4) -- Wi-Fi
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (2,5) -- Chỗ ngồi ưu tiên
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (2,6) -- Phòng chờ Thương gia
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (2,7) -- Lối đi ưu tiên (Fast Track)

-- First Class (3)
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,8) -- Hành lý 40kg
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,9) -- Suất ăn nóng cao cấp
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,4) -- Wi-Fi
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,5) -- Chỗ ngồi ưu tiên
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,6) -- Phòng chờ Thương gia
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,7) -- Lối đi ưu tiên (Fast Track)
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,10) -- Đưa đón sân bay xe sang
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,11) -- Bảo hiểm du lịch cao cấp
INSERT [dbo].[AmenitiesCabinType] ([CabinTypeID],[AmenityID]) VALUES (3,14) -- Bộ kit ngủ cao cấp
GO
